USE CACI;
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

drop table dbo.SALE_ORDER
go

CREATE TABLE dbo.SALE_ORDER
(
	ID					BIGINT		 NOT NULL IDENTITY,
	REFERENCE_NUMBER	BIGINT		 NULL UNIQUE,
	AMOUNT				BIGINT		 NOT NULL,
	DETAILS				VARCHAR(200) NOT NULL,
	ORDER_STATUS		VARCHAR(20)  NOT NULL,
	CREATED_DATE		DATETIME	NULL DEFAULT GETDATE(),
	CREATED_BY			VARCHAR(50)	NULL DEFAULT USER,
	MODIFIED_DATE		DATETIME	NULL DEFAULT GETDATE(),
	MODIFIED_BY			VARCHAR(50)	NULL DEFAULT USER,
	CONSTRAINT PK_ORDER PRIMARY KEY CLUSTERED 
	(
		ID ASC
	)
) 
GO

SET ANSI_PADDING OFF
GO


